### ISSUE TITLE
members seeing same stats as each other

### ISSUE THREAD

**Issue by joey2354** [DanielnetoDotCom/YouPHPTube#556]
Is this a bug ? can it be fixed ?

if not i think i might be leaving this platform sad to say ... it's a bit crazy this bug sorry, i think it'll turn too many members away and i don't have time to explain it to every member  ... hopefully can this be fixed ?

https://potads-vids.ml/charts

thank you. 

edit: https://potads-vids.ml/mvideos  when i click on the 'total views - view details' blue 1st box it doesn't show any videos, so i guess that's good.

**Comment by DanielnetoDotCom** [comment]
I see, the Dashboard is something else we need to improve.

Thanks for notice it

**Comment by joey2354** [comment]
:/

**Comment by joey2354** [comment]
you want to give us a refund buddy ... i'm too busy and ill to be playing games sorry to say, close to god etc etc etc.

or you want me take it to paypal ? 



thank you.

**Comment by joey2354** [comment]
reply wisely please

**Comment by joey2354** [comment]
i'm sorry man but i run a professional business and work with some big names in a certain field and i need it run correct .... i just don't have time to explain the views to every member who joins.


could this be fixed soon ? if so how soon ? if not i'll kindly request a refund so sorry to say.

**Comment by DanielnetoDotCom** [comment]
Sorry about that, but I think it is fixed now.

You will need to update your files and probably you will need to update the system as well.

https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-Update-your-YouPHPTube

If you want me to do this for you, please email me your YouPHPTube admin credentials

**Comment by joey2354** [comment]
thank you i'v emailed you.





thank you.

**Comment by DanielnetoDotCom** [comment]
Sorry, what happened?

**Comment by ChrisSlS** [comment]
I updated the charts.php and the system, but the problem remains the same : members seeing same stats as each other :/

**Comment by ChrisSlS** [comment]
I followed the intruction as shown here (method 1): 
https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-Update-your-YouPHPTube

All the files were updated is not it, where did I miss something ?

**Comment by DanielnetoDotCom** [comment]
@ChrisSlS not suppose to be the same. can you notice the same thing on demo site?

**Comment by ChrisSlS** [comment]
@DanielnetoDotCom  yes that's the same on the demo site.

![testdashboard](https://user-images.githubusercontent.com/37787071/38495595-75c47850-3bfa-11e8-836f-b4b05ada8f29.png)

**Comment by DanielnetoDotCom** [comment]
I see, you are talking about the hosting time, you right! it will be fixed

**Comment by ChrisSlS** [comment]
Thank you :) @DanielnetoDotCom

**Comment by DanielnetoDotCom** [comment]
@ChrisSlS try now

**Comment by ChrisSlS** [comment]
This works, thanks.

**Comment by hersche** [comment]
this seems to be solved completly, reopen in case of being wrong.
