### ISSUE TITLE
Embeded videos not working in Chrome and Firefox

### ISSUE THREAD

**Issue by eZweblogic** [DanielnetoDotCom/YouPHPTube#786]
Embeded videos work fine in Safari but not Chrome or Firefox. Chrome no embeded video will work while on Firefox it's a hit and miss, some play normal and some not.

Visiting the video website with either browser is normal and everything works fine, it's only wen embeding the videos that problem shows.

Any idea?

**Comment by DanielnetoDotCom** [comment]
what message are you getting when you trying to play?
can you screenshot your player?

**Comment by eZweblogic** [comment]
This is the message I get:
------------
The media could not be loaded, either because the server or network failed or because the format is not supported.
------------

from demo website I get the spinning wheel forever
![screen shot 2018-06-24 at 2 38 34 am](https://user-images.githubusercontent.com/6707978/41814529-0289dc92-7758-11e8-89f8-5a6455130c24.png)

![screen shot 2018-06-24 at 2 18 47 am](https://user-images.githubusercontent.com/6707978/41814476-1a3723c4-7756-11e8-926b-970e8c812351.png)

**Comment by DanielnetoDotCom** [comment]
What is the video link you are using?

**Comment by eZweblogic** [comment]
the embed code in share menu

**Comment by DanielnetoDotCom** [comment]
You suppose to use the URL not the embed code

**Comment by eZweblogic** [comment]
I'll try it and let you know what happens

**Comment by DanielnetoDotCom** [comment]
please share here the URL you are trying to use

**Comment by eZweblogic** [comment]
https://abbrak.live/cat/courses/video/business-01

**Comment by hersche** [comment]
it just works?

https://thepirate.party/2018/06/24/embed-test/

infinite loading.. mh, for me, this sounds like too many visitors on the server or too much streamers in your home-network or too far away to be connected.. but i am not shure if this is a problem of youphptube..

(i also have sometimes a bad connection to my demo-server.. not shure why, but basicly that's up to the hoster)

or do you embed it on a http://-site?

**Comment by eZweblogic** [comment]
Thank you,

Maybe long latency
It works fine on Safari, it's just Chrome on Mac and sometimes Firefox. I guess I'll leave at this.

Thanks again.

**Comment by hersche** [comment]
mh, yes, difficult to say what else it can be.. 

i did not see any kind of error directly. maybe it's a more intensive cache on safari? can't explain it, i have tested it with firefox on linux.

>  I guess I'll leave at this.

ok, i close the issue then. reopen if you feel like it's needed.

> Thanks again.

no problem :)

**Comment by eZweblogic** [comment]
I think there's a problem with embeded videos. Now even on Safari I get the same message.
No embeded video works.

When visiting the website itself everything works as expected, it's only embeded videos that suffer.
I'm hosting my website on a good VPS with almost Zero load because it's for a small group of students with most videos hidden

I have students from almost all parts of the world reporting same issue. I myself have a very good business dedicated internet connection.

This is serious for me, if I can't embed videos then the script is of no value. Actually all I need is the ability to embed videos.

**Comment by hersche** [comment]
so we reopen it.

can you provide me a url that embed the the video? 

can also be a simple html-file or so, which embeds a video.

personaly, it still works for me on my demo-site. again i have to ask: do you mix http and https (ssl and non-ssl)? i think that can be a problem.

**oh, and hey, you are using youphptube version 5.4 - we are all on 5.7. please do a update!! we fixed a lot of bugs in this time!**

**Comment by eZweblogic** [comment]
I updated to latest version 5.7 which went like a charm but embeded video problem persists.

try this url: https://abbrak.com/testing/

I'm using https on both websites https://abbrak.live and https://abbrak.com (wordpress)

**Comment by hersche** [comment]
in firefox https://abbrak.com/testing/ works perfectly fine for me.

in chromium, i can now confirm, it does not.. i will have a closer look there.

**Comment by hersche** [comment]
it is difficult to get the log-file of your installation, because of secure-videos-directory-plugin.

also, i found, that it gaves me a "invalid token" on some links in chromium. for testing, can you try disable that and look if it will work?

maybe it's a problem of combinations of the plugins. i can imagine, it's about resolution-switcher-plugin and secure-directory-plugin.

technical, why i think that? because secure-directory-plugin create a token per video. if there are 3 videolinks (resolution-switcher) and it always create ONE new token(overwrite the old), then only the last would be valid..

**Comment by eZweblogic** [comment]
OK solved, I disabled the secure video directory plugin and now all working fine.

Thank you hersch. I was on the verge of deleting the whole server and moving to another script but your dedication and prompt response saved the day. This shows the importance of timely tech support, and for me to slow down a bit hhhh

Thank you

**Comment by hersche** [comment]
very nice!

but it's still not solved, because this should work. ;)

@DanielnetoDotCom can you do a review by combine the video-resolution-plugin and secure-video-directory? i can imagine, thats a small thing for you.

**Comment by eZweblogic** [comment]
hhhh Daniel has to work extra hours

**Comment by DanielnetoDotCom** [comment]
Hi @eZweblogic 

the purpose of the "invalid token" from secure videos is to avoid anyone use your videos outside your site, so is not possible to embed videos from your site, they can only share your site link

**Comment by eZweblogic** [comment]
I understand what you mean Daniel. Thanks for everything
